### ISSUE TITLE
Replay works, but getevent not showing X, Y lines.

### ISSUE THREAD

**Issue by instasck** [Cartucho/android-touch-record-replay#14] opened 2019-09-22 20:16 UTC
this is what getevent sees:
```
[  182968.637659] 0003 0039 000009c0
[  182968.637659] 0001 014a 00000001
[  182968.637659] 0000 0000 00000000
[  182968.747814] 0003 0039 7fffffff
[  182968.747814] 0001 014a 00000000
[  182968.747814] 0000 0000 00000000
```

while the file is:
````
[  182160.523129] 0003 0039 000009c0
[  182160.523129] 0003 0035 00000039
[  182160.523129] 0003 0036 0000007c
[  182160.523129] 0001 014a 00000001
[  182160.632657] 0000 0000 00000000
[  182160.632657] 0003 0039 ffffffff
[  182160.632657] 0001 014a 00000000
[  182160.632657] 0000 0000 00000000
````

The bizzard is the click is in the correct place :()
The issue is that when I click the screen bymyself is do like the click from the screen was never "UP" so I see multitouch. but when sending another click to the screen with the software it is not a multitouch click but singe one.

**Comment by Cartucho** [comment] 2019-09-22 20:46
Can you try using Peter's technique: https://github.com/Cartucho/android-touch-record-replay/issues/12

**Comment by Cartucho** [comment] 2019-09-30 15:26
@instasck, this should be fixed. Could you please confirm?

**Comment by instasck** [comment] 2019-10-01 05:36
@Cartucho  this is not my isssue, I have seen last touch not recorded so I just remove it manually.
The issue is different as discribed ....

**Comment by Cartucho** [comment] 2019-10-02 08:35
Can you please update the code and give it a try? We made many changes in the last commits.

**Comment by instasck** [comment] 2019-10-04 05:50
@Cartucho I don't use the *.sh files ... I only use:
getevent -t  /dev/input/event1 | tee record_new
And split the file with my own code.

**Comment by Cartucho** [comment] 2019-10-04 14:34
oh ok, then the issue is not related to my code

**Closed as completed** 2019-10-04 14:36 UTC
